# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Enquête
gesloten: false
online: true

introductie: Je gaat een enquete invullen over een nieuw onderwijssysteem op Hageveld. Voordat je kan beginnen moet je eerst inloggen op Magister.
storing: We ondervinden momenteel een storing. Kom op een later moment terug.
geslotentekst: De enqu&#xEA;te is gesloten.
vraag1: Met welke vakken heb jij moeite?
vraag2: Voor welke vakken zou je extra uitdaging willen?
vraag3: Zou je extra activiteiten of vakken willen volgen als het beter binnen je rooster past?
vraag4: Zijn er activiteiten die je graag binnen school zou willen doen, die er nu niet zijn?
vraag5: Bij welke vakken verveel je je doordat je de stof al snapt?
vraag6: Vind je het prettig om op school ingeroosterde huiswerkmomenten te hebben, eventueel onder begeleiding van een vakdocent?
einde: Bedankt voor je deelname!

# Build settings
gems:
  - html-proofer

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - misc
  - script
  - Rakefile

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false

# Be sure to exclude vendor from your  _config.yml
# Travis bundles all gems in the vendor directory on its build servers, which Jekyll will mistakenly read and explode on.
# https://jekyllrb.com/docs/continuous-integration/
